### PR TITLE
Add new credential pictures

### PR DESCRIPTION
**Pull request by linuxgemini**
Signed-off-by: İlteriş Yağıztegin Eroğlu <ilteris@asenkron.com.tr>

### CODE REVIEW

**Comment by doegox** [comment]
thanks!

**Comment by doegox** [comment]
your pics are actually signed of by your nickname, is that ok or shall I inject your name and email in the EXIF ?

**Comment by doegox** [comment]
image

**Comment by linuxgemini** [comment]
@doegox If the page doesn't break on Turkish characters, go ahead. If it does, you can also use `Ilteris Yagiztegin Eroglu`

**Comment by doegox** [comment]
Well it broke but it's now fixed :)

**Pull request merged**
