### PR TITLE
Add from my collection

### PR DESCRIPTION
**Pull request by adryd325**
I'll need some help identifying the operating system the EMV stripe card runs, and I'm not sure if calypso falls under any iso specs.

### CODE REVIEW

**Comment by doegox** [comment]
A Calypso you can fill is usually ISO14443B-4 (which a phone should see, e.g. with NXP TagInfo).
Calypso throw away tickets are more ASK or CT ISO14443B-2 (which you cannot see with a phone but you can identify with libnfc)

**Comment by adryd325** [comment]
As for the stripe card, let me know if there's anything I can run against it to identify it. i've got a proxmark or acr122u to help with that

**Comment by doegox** [comment]
> As for the stripe card, let me know if there's anything I can run against it to identify it. i've got a proxmark or acr122u to help with that

For this collection, knowing if it's type A or type B is enough.
If you want to explore more there is the `hf emv` set of commands in the proxmark but I'm not very familiar with it.
You can discover what type of EMV apps are present (VISA, Amex,...) but you probably won't be able to tell what OS runs behind.

**Comment by doegox** [comment]
I'll merge as it is, thanks for your submission!

**Pull request merged**
